site_name: "LLM Matrix"
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_toc_entry: false
            show_category_heading: false
            toc_depth: 1
            members_order: source
            docstring_style: sphinx
  - mermaid2:
      version: 9.3.0
  - with-pdf
  - autorefs
  - mknotebooks:
      execute: false
markdown_extensions:
  - admonition
  - codehilite
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - tables
  - footnotes
  - attr_list
nav:
  - Home: index.md
  - Getting Started:
    - Tutorial: tutorial/index.md
  - User Guide:
    - Configuration: configuration/index.md
    - Metrics: metrics/index.md
    - Command Line Interface: cli.md
  - API Reference: api/index.md
  - Development:
    - Contributing: contributing.md
site_url: https://monarch-initiative.github.io/llm-matrix/
repo_url: https://github.com/monarch-initiative/llm-matrix/